Models/Dish.cs
namespace Restaurant.Models;

public class Dish
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;

    public string ImageUrl { get; set; } = null!;

    public double Price { get; set; }

    public List<DishIngredient>? DishIngredients { get; set; }

}

Models/DishIngredient.cs
namespace Restaurant.Models;

public class DishIngredient
{
    public int DishId { get; set; }
    public Dish? Dish { get; set; }
    public int IngredientId { get; set; }
    public Ingredient? Ingredient { get; set; }
}

Models/ErrorViewModel.cs
namespace Restaurant.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ingredient.cs
namespace Restaurant.Models;

public class Ingredient
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public List<DishIngredient>? DishIngredients { get; set; }
}

ViewModels/DishViewModel.cs
using Restaurant.Models;

namespace Restaurant.ViewModels;

public class DishViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public double Price { get; set; }
    public string ImageUrl { get; set; } = null!;
    public List<DishIngredient>? DishIngredients { get; set; }
    public List<IngredientViewModel>? Ingredients { get; set; }
    public string FormattedPrice => Price.ToString("C");

}

ViewModels/IngredientViewModel.cs
using Restaurant.Models;

namespace Restaurant.ViewModels;

public class IngredientViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public List<DishIngredient>? DishIngredients { get; set; }
    public List<DishViewModel>? Dishs { get; set; }
}

Controllers/DishController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Service;
using Restaurant.ViewModels;

namespace Restaurant.Controllers;

public class DishController : Controller
{
    private readonly IDishService _dishService;
    public DishController(IDishService dishService)
    {
        _dishService = dishService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var dishes = await _dishService.GetDishes();
        return View(dishes);
    }

    [HttpGet("Dish/Detail/{id}")]
    public async Task<IActionResult> Detail(int id)
    {
        var dish = await _dishService.GetDish(id);
        if (dish == null)
        {
            return NotFound();
        }
        return View(dish);
    }

    [HttpGet("Dish/Create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("Dish/Create")]
    public async Task<IActionResult> Create(DishViewModel dish)
    {
        if (ModelState.IsValid)
        {
            await _dishService.CreateDish(dish);
            return RedirectToAction("Index" , "Dish");
        }
        return View(dish);
    }

}

Controllers/IngredientController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Exceptions;
using Restaurant.Service;
using Restaurant.ViewModels;
using System.Threading.Tasks;

namespace Restaurant.Controllers;

public class IngredientController : Controller
{
    private readonly IIngredientService _ingredientService;
    public IngredientController(IIngredientService ingredientService)
    {
        _ingredientService = ingredientService;
    }

    //[HttpGet("Ingredient/Detail/{id}")]
    //public async Task<IActionResult> Detail(int id)
    //{
    //    var  ingredient = await _ingredientService.GetIngredient(id);
    //    if (ingredient == null)
    //    {
    //        return NotFound();
    //    }
    //    return View(ingredient);
    //}

    [HttpGet("Ingredient/Create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("Ingredient/Create")]
    public async Task<IActionResult> Create(IngredientViewModel ingredient)
    {
        try
        {
            if (ModelState.IsValid)
            {
                await _ingredientService.CreateIngredient(ingredient);
                return RedirectToAction("Index", "Dish");
            }
            return View(ingredient);
        }
        catch (DuplicateExeception ex)
        {
            TempData["ErrorMessage"] = ex.Message;
            return RedirectToAction("Index", "Dish");
        }
    }
    [HttpGet]
    public async Task<JsonResult> SearchIngredient(string name)
    {
        var ingredients = await _ingredientService.SearchIngredient(name);
        return Json(ingredients);
    }
}

Views/Dish/Create.cshtml
@model Restaurant.ViewModels.DishViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <form method="post" asp-controller="Dish" asp-action="Create" >
        <div>
            <label asp-for="Name" class="form-label">Enter Dish Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="ImageUrl" class="form-label">Upload Image URL</label>
            <input asp-for="ImageUrl" class="form-control" />
            <span asp-validation-for="ImageUrl" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Price" class="form-label">Dish Price</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

Views/Dish/Detail.cshtml
@model Restaurant.ViewModels.DishViewModel
@{
    ViewData["Title"] = "Detail";
}

<div class=" container">
    <h2>@Model.Name</h2>
    <img src="@Model.ImageUrl"/>
    <p>@Model.FormattedPrice</p>

    <div class="container">
        <h3>Ingredients</h3>
        @foreach (var ingredient in Model.Ingredients)
        {
            <p>@ingredient.Name</p>
        }
    </div>


</div>

Views/Dish/Index.cshtml
@using Restaurant.ViewModels
@model List<DishViewModel>
@{
    ViewBag.Title = "Restaurent";
}
<div class="container">
    <h2>Sri Lanakan Authentic Restuarent</h2>

    <div class="container mt-3">
        <div class="position-relative">
            <input id="searchText" name="name" class="form-control mx-2 mb-2" type="text" placeholder="Serching Ingredient" autocomplete="off"/>
            <div id="ingredientList" class="dropdown-menu w-100 position-absolute container" style="top:114%; left:0.5%;z-index:2;display:none" ></div>
        </div>
    </div>



    @if(TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show my-2" role="alert" >
            @TempData["ErrorMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close" ></button>
        </div>
    }


    @foreach (var dish in Model)
    {
        <div class="d-flex flex-column gap-3 mb-3">
            <a asp-controller="Dish" asp-action="Detail" asp-route-id="@dish.Id">
                <img src="@dish.ImageUrl"/>
            </a>
            <p>@dish.Name</p>
            <p>@dish.FormattedPrice</p>
        </div>
    }
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function(){
        function loadIngredient(query=""){
            $.ajax({
                url:"/Ingredient/SearchIngredient",
                type:"GET",
                data:{name:query},
                success:function(data){
                    if(data.length > 0){
                        $("#ingredientList").empty().show();
                        $.each(data, function(i,ingredient){
                            $("#ingredientList").append(`<a href="#" class="dropdown-item">${ingredient.name}</a>`);
                        });
                    }else if(query.length>0){
                        $("#ingredientList").empty().show();
                        $("#ingredientList").append(`<span class="dropdown-item text-muted">No results found</span>`);
                    }}
            })
        }
        loadIngredient();

        $(document).on("click", ".dropdown-item", function () {
            if(data.length>0){
                $("#searchText").val($(this).text());
                $("#ingredientList").hide();
            }
        });

         $(document).click(function (e) {
            if (!$(e.target).closest('.position-relative').length) {
                $("#ingredientList").hide();
            }
        });

        $("#searchText").on("keyup", function(){
            var value = $(this).val();
            if(value.length > 0){
                loadIngredient(value);
            }else{
                $("#ingredientList").hide();   
            }
        } );
    });
</script>

Views/Ingredient/Create.cshtml
@model Restaurant.ViewModels.IngredientViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <form asp-controller="Ingredient" asp-action="Create" method="post">
        <div class="form-grop mb-3">
            <label asp-for="Name" class="form-label" >Enter Ingredient</label>
            <input asp-for="Name" type="text" class="form-control" placeholder="Enter Ingredient" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" >Submit</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restaurant.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dish" asp-action="Index">Restaurant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Create">New Dish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Create">New Ingredient</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>